spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/Coding_Platform
        username: postgres
        password: Loknishu1!
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true

logging:
    level:
        root: INFO